# Generated by Django 5.2.13 on 2026-04-30 15:49

import diario_bordo.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0021_config_pt_sede_chefia_coord'),
        ('eventos', '0058_oficioassinaturapedido_criado_por_nome_and_more'),
        ('prestacao_contas', '0007_prestacaoconta_comprovante_transferencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioBordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oficio', models.CharField(blank=True, default='', max_length=80, verbose_name='Numero do oficio')),
                ('e_protocolo', models.CharField(blank=True, default='', max_length=80, verbose_name='E-protocolo')),
                ('divisao', models.CharField(blank=True, default='', max_length=160, verbose_name='Divisao')),
                ('unidade_cabecalho', models.CharField(blank=True, default='', max_length=180, verbose_name='Unidade')),
                ('tipo_veiculo', models.CharField(blank=True, default='', max_length=80, verbose_name='Tipo do veiculo')),
                ('combustivel', models.CharField(blank=True, default='', max_length=80, verbose_name='Combustivel')),
                ('placa_oficial', models.CharField(blank=True, default='', max_length=20, verbose_name='Placa oficial')),
                ('placa_reservada', models.CharField(blank=True, default='', max_length=20, verbose_name='Placa reservada')),
                ('nome_responsavel', models.CharField(blank=True, default='', max_length=160, verbose_name='Nome do responsavel')),
                ('rg_responsavel', models.CharField(blank=True, default='', max_length=40, verbose_name='RG do responsavel')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('gerado', 'Gerado'), ('assinado', 'Assinado'), ('cancelado', 'Cancelado')], db_index=True, default='rascunho', max_length=20)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to=diario_bordo.models.diario_pdf_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('arquivo_docx', models.FileField(blank=True, null=True, upload_to=diario_bordo.models.diario_docx_upload_to)),
                ('arquivo_xlsx', models.FileField(blank=True, null=True, upload_to=diario_bordo.models.diario_xlsx_upload_to)),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to=diario_bordo.models.diario_assinado_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_bordo_motorista', to='cadastros.viajante', verbose_name='Motorista/responsavel')),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_bordo', to='eventos.oficio', verbose_name='Oficio vinculado')),
                ('prestacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_bordo', to='prestacao_contas.prestacaoconta', verbose_name='Prestacao de contas')),
                ('roteiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_bordo', to='eventos.roteiroevento', verbose_name='Roteiro vinculado')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_bordo', to='cadastros.veiculo', verbose_name='Viatura/veiculo')),
            ],
            options={
                'verbose_name': 'Diario de Bordo',
                'verbose_name_plural': 'Diarios de Bordo',
                'ordering': ['-atualizado_em', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DiarioBordoTrecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de saida')),
                ('hora_saida', models.TimeField(blank=True, null=True, verbose_name='Hora de saida')),
                ('km_inicial', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM inicial')),
                ('data_chegada', models.DateField(blank=True, null=True, verbose_name='Data de chegada')),
                ('hora_chegada', models.TimeField(blank=True, null=True, verbose_name='Hora de chegada')),
                ('km_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM final')),
                ('origem', models.CharField(max_length=160)),
                ('destino', models.CharField(max_length=160)),
                ('necessidade_abastecimento', models.BooleanField(default=False, verbose_name='Necessidade de abastecimento')),
                ('observacao', models.TextField(blank=True, default='')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='diario_bordo.diariobordo')),
            ],
            options={
                'verbose_name': 'Trecho do Diario de Bordo',
                'verbose_name_plural': 'Trechos do Diario de Bordo',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
