# Generated by Django 5.2.12 on 2026-03-05 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='Sigla')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(blank=True, max_length=20, verbose_name='Prefixo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('combustivel', models.CharField(max_length=50, verbose_name='Combustível')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Viajante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('unidade_lotacao', models.CharField(blank=True, max_length=150, verbose_name='Unidade de lotação')),
                ('is_ascom', models.BooleanField(default=False, verbose_name='ASCOM')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Viajante',
                'verbose_name_plural': 'Viajantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_justificativa_dias', models.PositiveIntegerField(default=10, verbose_name='Prazo justificativa (dias)')),
                ('nome_orgao', models.CharField(blank=True, max_length=200, verbose_name='Nome do órgão')),
                ('sigla_orgao', models.CharField(blank=True, max_length=20, verbose_name='Sigla do órgão')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cidade_sede_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.cidade', verbose_name='Cidade sede padrão')),
            ],
            options={
                'verbose_name': 'Configuração do sistema',
                'verbose_name_plural': 'Configurações do sistema',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='cadastros.estado', verbose_name='Estado'),
        ),
    ]
