# Generated by Django 5.2.12 on 2026-03-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='codigo_ibge',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='Código IBGE'),
        ),
        migrations.AddField(
            model_name='estado',
            name='codigo_ibge',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, verbose_name='Código IBGE'),
        ),
    ]
