# Generated by Django 6.0.1 on 2026-03-05 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_add_codigo_ibge'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='assinatura_justificativas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.viajante', verbose_name='Assinatura Justificativas'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='assinatura_oficio_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.viajante', verbose_name='Assinatura Ofícios 1'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='assinatura_oficio_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.viajante', verbose_name='Assinatura Ofícios 2'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='assinatura_ordens_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.viajante', verbose_name='Assinatura Ordens de Serviço'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='assinatura_planos_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.viajante', verbose_name='Assinatura Planos de Trabalho'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='cidade_endereco',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Cidade (endereço)'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='divisao',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Divisão'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='logradouro',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='uf',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='unidade',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Unidade'),
        ),
    ]
