# Generated by Django 5.2.13 on 2026-05-04 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_cidade_ativa_remove_motorista_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='servidor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='motorista', to='cadastros.servidor'),
        ),
    ]
