# Generated by Django 6.0.1 on 2026-03-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_normalizar_dados_unicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajante',
            name='nome',
            field=models.CharField(max_length=160, unique=True, verbose_name='Nome'),
        ),
        migrations.AddConstraint(
            model_name='viajante',
            constraint=models.UniqueConstraint(condition=models.Q(('rg__gt', ''), models.Q(('rg', 'NAO POSSUI RG'), _negated=True)), fields=('rg',), name='cadastros_viajante_rg_unique'),
        ),
        migrations.AddConstraint(
            model_name='viajante',
            constraint=models.UniqueConstraint(condition=models.Q(('telefone__gt', '')), fields=('telefone',), name='cadastros_viajante_telefone_unique'),
        ),
    ]
