# Generated by Django 6.0.1 on 2026-03-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_viajante_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeLotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=30, unique=True, verbose_name='Sigla')),
                ('nome', models.CharField(max_length=160, unique=True, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidade de lotação',
                'verbose_name_plural': 'Unidades de lotação',
                'ordering': ['sigla'],
            },
        ),
    ]
