# Generated by Django 6.0.1 on 2026-03-06

from django.db import migrations, models
from django.db.models import Q


def marcar_existentes_finalizado(apps, schema_editor):
    Viajante = apps.get_model('cadastros', 'Viajante')
    Viajante.objects.all().update(status='FINALIZADO')


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_veiculo_status_tipo_placa_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajante',
            name='status',
            field=models.CharField(
                choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')],
                default='RASCUNHO',
                max_length=20,
                verbose_name='Status',
            ),
        ),
        migrations.AlterField(
            model_name='viajante',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Nome'),
        ),
        migrations.AddConstraint(
            model_name='viajante',
            constraint=models.UniqueConstraint(
                condition=Q(('nome__gt', '')),
                fields=('nome',),
                name='cadastros_viajante_nome_unique_preenchido',
            ),
        ),
        migrations.RunPython(marcar_existentes_finalizado, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='viajante',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Viajante', 'verbose_name_plural': 'Viajantes'},
        ),
    ]
