# Generated by Django 6.0.1 on 2026-03-05 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_add_codigo_ibge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo_demanda', models.CharField(choices=[('PCPR_NA_COMUNIDADE', 'PCPR na Comunidade'), ('OPERACAO_POLICIAL', 'Operação Policial'), ('PARANA_EM_ACAO', 'Paraná em Ação'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Tipo de demanda')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(verbose_name='Data de término')),
                ('tem_convite_ou_oficio_evento', models.BooleanField(default=False, verbose_name='Tem convite/ofício solicitante?')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado'), ('ARQUIVADO', 'Arquivado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cidade_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_cidade_base', to='cadastros.cidade', verbose_name='Cidade base')),
                ('cidade_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_cidade_principal', to='cadastros.cidade', verbose_name='Cidade principal')),
                ('estado_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_estado_principal', to='cadastros.estado', verbose_name='Estado principal')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio', '-created_at'],
            },
        ),
    ]
