# Generated by Django 6.0.1 on 2026-03-06 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_viajante_status_nome_rascunho'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoteiroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida_dt', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora saída')),
                ('duracao_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (min)')),
                ('chegada_dt', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora chegada')),
                ('retorno_saida_dt', models.DateTimeField(blank=True, null=True, verbose_name='Retorno — saída')),
                ('retorno_duracao_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Retorno — duração (min)')),
                ('retorno_chegada_dt', models.DateTimeField(blank=True, null=True, verbose_name='Retorno — chegada')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destino_cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.cidade', verbose_name='Cidade destino')),
                ('destino_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.estado', verbose_name='Estado destino')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roteiros', to='eventos.evento', verbose_name='Evento')),
                ('origem_cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.cidade', verbose_name='Cidade origem')),
                ('origem_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.estado', verbose_name='Estado origem')),
            ],
            options={
                'verbose_name': 'Roteiro do evento',
                'verbose_name_plural': 'Roteiros do evento',
                'ordering': ['-created_at'],
            },
        ),
    ]
