# Generated by Django (refatoração Etapa 1)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_viajante_status_nome_rascunho'),
        ('eventos', '0002_roteiro_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDemandaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('descricao_padrao', models.TextField(blank=True, default='', verbose_name='Descrição padrão')),
                ('ordem', models.PositiveIntegerField(default=100, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_outros', models.BooleanField(default=False, verbose_name='É "Outros"')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de demanda (evento)',
                'verbose_name_plural': 'Tipos de demanda (evento)',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='data_unica',
            field=models.BooleanField(default=False, verbose_name='Evento em um único dia'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipos_demanda',
            field=models.ManyToManyField(blank=True, related_name='eventos', to='eventos.tipodemandaevento', verbose_name='Tipos de demanda'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo_demanda',
            field=models.CharField(blank=True, choices=[('PCPR_NA_COMUNIDADE', 'PCPR na Comunidade'), ('OPERACAO_POLICIAL', 'Operação Policial'), ('PARANA_EM_ACAO', 'Paraná em Ação'), ('OUTRO', 'Outro')], max_length=30, null=True, verbose_name='Tipo de demanda (legado)'),
        ),
        migrations.CreateModel(
            name='EventoDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evento_destinos', to='cadastros.cidade', verbose_name='Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evento_destinos', to='cadastros.estado', verbose_name='Estado')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Destino do evento',
                'verbose_name_plural': 'Destinos do evento',
                'ordering': ['evento', 'ordem', 'cidade__nome'],
            },
        ),
    ]
