# Generated by Django 6.0.1 on 2026-03-09 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_viajante_status_nome_rascunho'),
        ('eventos', '0005_roteiro_destinos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roteiroevento',
            name='origem_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.cidade', verbose_name='Cidade sede'),
        ),
        migrations.AlterField(
            model_name='roteiroevento',
            name='origem_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.estado', verbose_name='Estado sede'),
        ),
        migrations.CreateModel(
            name='RoteiroEventoTrecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('tipo', models.CharField(choices=[('IDA', 'Ida'), ('RETORNO', 'Retorno')], default='IDA', max_length=10, verbose_name='Tipo')),
                ('saida_dt', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
                ('chegada_dt', models.DateTimeField(blank=True, null=True, verbose_name='Chegada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destino_cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.cidade', verbose_name='Cidade destino')),
                ('destino_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.estado', verbose_name='Estado destino')),
                ('origem_cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.cidade', verbose_name='Cidade origem')),
                ('origem_estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.estado', verbose_name='Estado origem')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='eventos.roteiroevento', verbose_name='Roteiro')),
            ],
            options={
                'verbose_name': 'Trecho do roteiro',
                'verbose_name_plural': 'Trechos do roteiro',
                'ordering': ['roteiro', 'ordem'],
            },
        ),
    ]
