# Generated by Django 6.0.1 on 2026-03-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_roteiro_evento_trecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiroeventotrecho',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preenchido manualmente ou via "Calcular km" (Google Routes).', max_digits=8, null=True, verbose_name='Distância (km)'),
        ),
        migrations.AddField(
            model_name='roteiroeventotrecho',
            name='duracao_estimada_min',
            field=models.PositiveIntegerField(blank=True, help_text='Preenchido manualmente ou via "Calcular km".', null=True, verbose_name='Duração estimada (min)'),
        ),
        migrations.AddField(
            model_name='roteiroeventotrecho',
            name='rota_calculada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rota calculada em'),
        ),
        migrations.AddField(
            model_name='roteiroeventotrecho',
            name='rota_fonte',
            field=models.CharField(blank=True, default='', help_text='Ex.: GOOGLE quando calculado pela API.', max_length=30, verbose_name='Fonte da rota'),
        ),
    ]
