# Generated by Django 6.0.1 on 2026-03-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_trecho_distancia_duracao_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiroeventotrecho',
            name='tempo_adicional_min',
            field=models.IntegerField(blank=True, default=0, help_text='Folga ajustável pelo usuário (botões ±15 min).', null=True, verbose_name='Tempo adicional (min)'),
        ),
        migrations.AddField(
            model_name='roteiroeventotrecho',
            name='tempo_cru_estimado_min',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo base da viagem (estimativa local), somente leitura.', null=True, verbose_name='Tempo cru estimado (min)'),
        ),
        migrations.AlterField(
            model_name='roteiroeventotrecho',
            name='distancia_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preenchido manualmente ou via "Estimar km/tempo" (estimativa local).', max_digits=8, null=True, verbose_name='Distância (km)'),
        ),
        migrations.AlterField(
            model_name='roteiroeventotrecho',
            name='duracao_estimada_min',
            field=models.PositiveIntegerField(blank=True, help_text='tempo_total_final = tempo_cru + tempo_adicional. Mantido para compatibilidade.', null=True, verbose_name='Duração estimada (min)'),
        ),
        migrations.AlterField(
            model_name='roteiroeventotrecho',
            name='rota_fonte',
            field=models.CharField(blank=True, default='', help_text='Ex.: ESTIMATIVA_LOCAL quando calculado pela estimativa local.', max_length=30, verbose_name='Fonte da rota'),
        ),
    ]
