# Generated by Django 6.0.1 on 2026-03-10 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_cidade_latitude_longitude'),
        ('eventos', '0008_add_tempo_cru_adicional_trecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_motorista', to='cadastros.viajante', verbose_name='Motorista'),
        ),
        migrations.AddField(
            model_name='evento',
            name='observacoes_operacionais',
            field=models.TextField(blank=True, default='', verbose_name='Observações operacionais'),
        ),
        migrations.AddField(
            model_name='evento',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_veiculo', to='cadastros.veiculo', verbose_name='Veículo'),
        ),
        migrations.CreateModel(
            name='EventoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='eventos.evento', verbose_name='Evento')),
                ('viajante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_participacao', to='cadastros.viajante', verbose_name='Viajante')),
            ],
            options={
                'verbose_name': 'Participante do evento',
                'verbose_name_plural': 'Participantes do evento',
                'ordering': ['evento', 'ordem', 'viajante__nome'],
                'constraints': [models.UniqueConstraint(fields=('evento', 'viajante'), name='eventos_eventoparticipante_evento_viajante_unique')],
            },
        ),
    ]
