# Generated by Django 6.0.1 on 2026-03-10 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_etapa3_composicao_viagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Número')),
                ('ano', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Ano')),
                ('protocolo', models.CharField(blank=True, default='', max_length=80, verbose_name='Protocolo')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], db_index=True, default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oficios', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Ofício',
                'verbose_name_plural': 'Ofícios',
                'ordering': ['-created_at'],
            },
        ),
    ]
