# Generated by Django 6.0.1 on 2026-03-10 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_cidade_latitude_longitude'),
        ('eventos', '0010_oficio_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='carona_oficio_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_que_usam_carona', to='eventos.oficio', verbose_name='Ofício referência (carona)'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='combustivel',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Combustível'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='custeio_tipo',
            field=models.CharField(blank=True, choices=[('UNIDADE', 'UNIDADE - DPC (diárias e combustível custeados pela DPC).'), ('OUTRA_INSTITUICAO', 'OUTRA INSTITUIÇÃO'), ('ONUS_LIMITADOS', 'ÔNUS LIMITADOS AOS PRÓPRIOS VENCIMENTOS')], default='UNIDADE', max_length=30, verbose_name='Custeio'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motivo',
            field=models.TextField(blank=True, default='', verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Motorista (nome)'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_carona',
            field=models.BooleanField(default=False, verbose_name='Motorista carona'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_oficio',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Ofício do motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_oficio_ano',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano ofício motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_oficio_numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nº ofício motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_protocolo',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Protocolo motorista'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='motorista_viajante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_motorista', to='cadastros.viajante', verbose_name='Motorista (viajante)'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='nome_instituicao_custeio',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome instituição de custeio'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='placa',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Placa'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='tipo_destino',
            field=models.CharField(blank=True, choices=[('INTERIOR', 'Interior'), ('CAPITAL', 'Capital'), ('BRASILIA', 'Brasília')], default='', max_length=20, verbose_name='Tipo destino'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='tipo_viatura',
            field=models.CharField(blank=True, choices=[('CARACTERIZADA', 'Caracterizada'), ('DESCARACTERIZADA', 'Descaracterizada')], default='DESCARACTERIZADA', max_length=20, verbose_name='Tipo viatura'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='cadastros.veiculo', verbose_name='Veículo'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='viajantes',
            field=models.ManyToManyField(blank=True, related_name='oficios', to='cadastros.viajante', verbose_name='Viajantes'),
        ),
    ]
