# Generated by Django 5.2.12 on 2026-03-10 12:11

import django.db.models.deletion
from django.db import migrations, models
from datetime import date
from django.utils import timezone


def backfill_oficio_data(apps, schema_editor):
    Oficio = apps.get_model('eventos', 'Oficio')
    OficioCounter = apps.get_model('eventos', 'OficioCounter')
    db_alias = schema_editor.connection.alias

    for oficio in Oficio.objects.using(db_alias).all():
        needs_save = False
        if not oficio.data_criacao:
            if oficio.created_at:
                oficio.data_criacao = oficio.created_at.date()
            elif oficio.ano:
                oficio.data_criacao = date(int(oficio.ano), 1, 1)
            else:
                oficio.data_criacao = timezone.localdate()
            needs_save = True
        if needs_save:
            oficio.save(update_fields=['data_criacao'])

    agregados = (
        Oficio.objects.using(db_alias)
        .exclude(ano__isnull=True)
        .exclude(numero__isnull=True)
        .values('ano')
        .annotate(max_num=models.Max('numero'))
    )
    for row in agregados:
        OficioCounter.objects.using(db_alias).update_or_create(
            ano=int(row['ano']),
            defaults={'last_numero': int(row['max_num'] or 0)},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_cidade_latitude_longitude'),
        ('eventos', '0011_oficio_campos_legado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloMotivoViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do modelo')),
                ('texto', models.TextField(verbose_name='Texto do motivo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de motivo',
                'verbose_name_plural': 'Modelos de motivo',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='OficioCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True)),
                ('last_numero', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contador de ofício',
                'verbose_name_plural': 'Contadores de ofício',
            },
        ),
        migrations.AddField(
            model_name='oficio',
            name='data_criacao',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='oficio',
            name='modelo_motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='eventos.modelomotivoviagem', verbose_name='Modelo de motivo'),
        ),
        migrations.AddConstraint(
            model_name='oficio',
            constraint=models.UniqueConstraint(fields=('ano', 'numero'), name='eventos_oficio_numero_ano_unique'),
        ),
        migrations.RunPython(backfill_oficio_data, migrations.RunPython.noop),
    ]
