# Generated by Django 5.2.12 on 2026-03-10 12:38

from django.db import migrations


def normalize_protocolos(apps, schema_editor):
    Oficio = apps.get_model('eventos', 'Oficio')
    db_alias = schema_editor.connection.alias
    for oficio in Oficio.objects.using(db_alias).all():
        protocolo_raw = str(oficio.protocolo or '')
        protocolo_digits = ''.join(ch for ch in protocolo_raw if ch.isdigit())
        if protocolo_digits != protocolo_raw:
            oficio.protocolo = protocolo_digits
            oficio.save(update_fields=['protocolo'])


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_modelomotivoviagem_oficiocounter_oficio_data_criacao_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_protocolos, migrations.RunPython.noop),
    ]
