# Generated by Django 6.0.1 on 2026-03-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_normalize_oficio_protocolos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OficioCounter',
        ),
        migrations.AlterModelOptions(
            name='modelomotivoviagem',
            options={'ordering': ['nome'], 'verbose_name': 'Modelo de motivo', 'verbose_name_plural': 'Modelos de motivo'},
        ),
        migrations.AlterField(
            model_name='roteiroevento',
            name='retorno_chegada_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retorno - chegada'),
        ),
        migrations.AlterField(
            model_name='roteiroevento',
            name='retorno_duracao_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Retorno - duração (min)'),
        ),
        migrations.AlterField(
            model_name='roteiroevento',
            name='retorno_saida_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retorno - saída'),
        ),
    ]
