# Generated by Django 6.0.1 on 2026-03-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0031_ordemservico_documentoavulso_ordem_servico_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventoFundamentacao',
        ),
    ]
