# Generated by Django 5.2.12 on 2026-03-18 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0032_delete_eventofundamentacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficio',
            name='justificativa_modelo',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='justificativa_texto',
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, default='', verbose_name='Texto da justificativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas', to='eventos.modelojustificativa', verbose_name='Modelo de justificativa')),
                ('oficio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificativa', to='eventos.oficio', verbose_name='Ofício')),
            ],
            options={
                'verbose_name': 'Justificativa',
                'verbose_name_plural': 'Justificativas',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
