# Generated by Django 6.0.1 on 2026-03-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0035_termoautorizacao_oficios_delete_documentoavulso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termoautorizacao',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='termoautorizacao',
            name='texto_complementar',
        ),
    ]
