# Generated by Django 5.2.12 on 2026-03-20 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0036_remove_termoautorizacao_observacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotrabalho',
            name='destinos_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Destinos estruturados'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='diarias_quantidade',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Simulação de diárias (quantidade)'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='diarias_valor_extenso',
            field=models.TextField(blank=True, default='', verbose_name='Simulação de diárias (valor por extenso)'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='diarias_valor_total',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Simulação de diárias (valor total)'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='diarias_valor_unitario',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Simulação de diárias (valor unitário)'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='evento_data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data final do evento'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='evento_data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data inicial do evento'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='evento_data_unica',
            field=models.BooleanField(default=False, verbose_name='Evento em um único dia'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='oficios',
            field=models.ManyToManyField(blank=True, related_name='planos_trabalho_relacionados', to='eventos.oficio', verbose_name='Ofícios relacionados'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='roteiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_trabalho', to='eventos.roteiroevento', verbose_name='Roteiro selecionado'),
        ),
    ]
