# Generated by Django 6.0.1 on 2026-03-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0037_planotrabalho_destinos_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planotrabalho',
            name='efetivo_resumo',
        ),
        migrations.RemoveField(
            model_name='planotrabalho',
            name='locais',
        ),
        migrations.RemoveField(
            model_name='planotrabalho',
            name='objetivo',
        ),
    ]
