# Generated by Django 6.0.1 on 2026-03-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0038_remove_planotrabalho_efetivo_resumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='assunto_tipo',
            field=models.CharField(blank=True, choices=[('AUTORIZACAO', 'Autorização'), ('CONVALIDACAO', 'Convalidação')], default='AUTORIZACAO', max_length=20, verbose_name='Tipo do assunto'),
        ),
    ]
