# Generated by Django 5.2.12 on 2026-03-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0039_oficio_assunto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotrabalho',
            name='coordenadores',
            field=models.ManyToManyField(blank=True, related_name='planos_trabalho_coordenando', to='eventos.coordenadoroperacional', verbose_name='Coordenadores'),
        ),
    ]
