# Generated by Django 5.2.12 on 2026-03-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0040_planotrabalho_coordenadores_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotrabalho',
            name='quantidade_diarias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Quantidade de diárias (decimal)'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='valor_diarias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor total de diárias'),
        ),
        migrations.AddField(
            model_name='planotrabalho',
            name='valor_diarias_extenso',
            field=models.TextField(blank=True, default='', verbose_name='Valor total de diárias por extenso'),
        ),
    ]
