# Generated by Django 5.2.12 on 2026-03-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0043_planotrabalho_campos_calculadora_diarias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeplanotrabalho',
            name='codigo',
            field=models.CharField(max_length=40, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='atividadeplanotrabalho',
            name='recurso_necessario',
            field=models.TextField(verbose_name='Recursos necessários'),
        ),
    ]
