# Generated by Django 5.2.12 on 2026-04-08 18:04

import django.db.models.deletion
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0047_ordemservico_campos_documentais'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAnexoSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=eventos.models.evento_anexo_solicitante_upload_to, verbose_name='Arquivo (PDF)')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome original')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de upload')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_solicitante', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Anexo de convite/ofício do evento',
                'verbose_name_plural': 'Anexos de convite/ofício do evento',
                'ordering': ['ordem', '-uploaded_at', 'id'],
            },
        ),
    ]
