# Generated by Django 5.2.12 on 2026-04-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0048_eventoanexosolicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiroevento',
            name='quantidade_diarias',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Quantidade de diárias'),
        ),
        migrations.AddField(
            model_name='roteiroevento',
            name='valor_diarias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor das diárias'),
        ),
        migrations.AddField(
            model_name='roteiroevento',
            name='valor_diarias_extenso',
            field=models.TextField(blank=True, default='', verbose_name='Valor das diárias por extenso'),
        ),
    ]
