# Generated by Django 5.2.12 on 2026-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0049_add_roteiroevento_diarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='planotrabalho',
            name='step2_origem_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Origem da etapa 2'),
        ),
    ]
