# Generated by Django 6.0.1 on 2026-04-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0050_planotrabalho_step2_origem_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='designacoes',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='determinacoes',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_deslocamento_fim',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data final do deslocamento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_unica',
            field=models.BooleanField(default=True, verbose_name='Data única'),
        ),
    ]
