# Generated by Django 6.0.1 on 2026-04-16 17:01

import django.db.models.deletion
from django.db import migrations, models


def forwards_copiar_evento_para_vinculos(apps, schema_editor):
    Oficio = apps.get_model('eventos', 'Oficio')
    OficioEventoVinculo = apps.get_model('eventos', 'OficioEventoVinculo')
    for oficio in Oficio.objects.exclude(evento_id__isnull=True).iterator():
        OficioEventoVinculo.objects.get_or_create(
            oficio_id=oficio.pk,
            evento_id=oficio.evento_id,
        )


def backwards_sem_acao(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0052_termoautorizacao_saneia_oficio_canonico'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioEventoVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'evento',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vinculos_oficio_evento',
                        to='eventos.evento',
                        verbose_name='Evento',
                    ),
                ),
                (
                    'oficio',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vinculos_evento',
                        to='eventos.oficio',
                        verbose_name='Ofício',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Vínculo ofício com evento',
                'verbose_name_plural': 'Vínculos ofício com evento',
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='oficioeventovinculo',
            constraint=models.UniqueConstraint(
                fields=('oficio', 'evento'),
                name='eventos_oficioeventovinculo_unique',
            ),
        ),
        migrations.RunPython(forwards_copiar_evento_para_vinculos, backwards_sem_acao),
        migrations.RemoveField(
            model_name='oficio',
            name='evento',
        ),
        migrations.AddField(
            model_name='oficio',
            name='eventos',
            field=models.ManyToManyField(
                blank=True,
                related_name='oficios',
                through='eventos.OficioEventoVinculo',
                to='eventos.evento',
                verbose_name='Eventos vinculados',
            ),
        ),
    ]
