# Generated by Django 5.2.12 on 2026-04-16 18:13

import django.db.models.deletion
from django.db import migrations, models


def _classificar_derivacao_termo(apps, schema_editor):
    TermoAutorizacao = apps.get_model('eventos', 'TermoAutorizacao')
    db_alias = schema_editor.connection.alias

    TermoAutorizacao.objects.using(db_alias).filter(viajante_id__isnull=False).update(
        derivacao_tipo='SERVIDOR',
    )
    TermoAutorizacao.objects.using(db_alias).filter(
        viajante_id__isnull=True,
        veiculo_id__isnull=False,
    ).update(derivacao_tipo='VIATURA')
    TermoAutorizacao.objects.using(db_alias).filter(
        viajante_id__isnull=True,
        veiculo_id__isnull=True,
    ).update(derivacao_tipo='GENERICA')


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0053_oficio_eventos_vinculo_explicito'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoautorizacao',
            name='derivacao_tipo',
            field=models.CharField(choices=[('GENERICA', 'Termo generico'), ('SERVIDOR', 'Servidor'), ('VIATURA', 'Viatura')], db_index=True, default='SERVIDOR', max_length=20, verbose_name='Tipo da derivacao'),
        ),
        migrations.AddField(
            model_name='termoautorizacao',
            name='termo_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivacoes', to='eventos.termoautorizacao', verbose_name='Termo pai'),
        ),
        migrations.RunPython(_classificar_derivacao_termo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='termoautorizacao',
            name='modo_geracao',
            field=models.CharField(choices=[('GENERICA', 'Termo generico do evento'), ('RAPIDO', 'Termo rapido'), ('AUTOMATICO_COM_VIATURA', 'Automatico com viatura'), ('AUTOMATICO_SEM_VIATURA', 'Automatico sem viatura')], db_index=True, default='RAPIDO', max_length=40, verbose_name='Modo de geracao'),
        ),
    ]
