# Generated by Django 6.0.1 on 2026-04-17 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('eventos', '0054_termoautorizacao_derivacao_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioDocumentoVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(db_index=True, max_length=40, verbose_name='Tipo de documento')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='ID do documento')),
                ('documento_rotulo', models.CharField(blank=True, default='', max_length=255, verbose_name='Rótulo do documento')),
                ('status_compatibilidade', models.CharField(choices=[('COMPATIVEL', 'Compatível'), ('CONFLITO', 'Conflito')], db_index=True, default='COMPATIVEL', max_length=20, verbose_name='Status de compatibilidade')),
                ('snapshot_oficio', models.JSONField(blank=True, default=dict, verbose_name='Snapshot do ofício')),
                ('snapshot_documento', models.JSONField(blank=True, default=dict, verbose_name='Snapshot do documento')),
                ('campos_herdados_oficio', models.JSONField(blank=True, default=list, verbose_name='Campos herdados do ofício')),
                ('campos_herdados_documento', models.JSONField(blank=True, default=list, verbose_name='Campos herdados do documento')),
                ('conflitos', models.JSONField(blank=True, default=list, verbose_name='Conflitos')),
                ('observacoes', models.JSONField(blank=True, default=list, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_oficio_documento_vinculos', to='contenttypes.contenttype', verbose_name='Tipo de conteúdo')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_vinculados', to='eventos.oficio', verbose_name='Ofício')),
            ],
            options={
                'verbose_name': 'Vínculo documental do ofício',
                'verbose_name_plural': 'Vínculos documentais do ofício',
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('oficio', 'content_type', 'object_id'), name='eventos_oficiodocumentovinculo_unique')],
            },
        ),
    ]
