# Generated by Django 6.0.1 on 2026-04-17 17:24

import django.db.models.deletion
from django.db import migrations, models


def limpar_dados_orfaos_eventos(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            DELETE FROM eventos_eventoparticipante
            WHERE evento_id NOT IN (SELECT id FROM eventos_evento)
            """
        )
        cursor.execute(
            """
            DELETE FROM eventos_evento_tipos_demanda
            WHERE evento_id NOT IN (SELECT id FROM eventos_evento)
            """
        )
        cursor.execute(
            """
            DELETE FROM eventos_efetivoplanotrabalhodocumento
            WHERE plano_trabalho_id NOT IN (SELECT id FROM eventos_planotrabalho)
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('eventos', '0055_oficiodocumentovinculo'),
    ]

    operations = [
        migrations.RunPython(limpar_dados_orfaos_eventos, migrations.RunPython.noop),
        migrations.CreateModel(
            name='EventoDocumentoSugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='ID do documento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RESOLVIDA', 'Resolvida'), ('DESCARTADA', 'Descartada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Candidatos e motivos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sugestão de evento para documento',
                'verbose_name_plural': 'Sugestões de evento para documentos',
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EventoResgateAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('AUTO_ANEXOU', 'Anexado automaticamente'), ('SUGESTAO', 'Sugestão / ambiguidade'), ('IGNOROU_BAIXA_CONFIANCA', 'Ignorado (baixa confiança)'), ('SEM_CANDIDATO', 'Sem candidato compatível')], db_index=True, max_length=40, verbose_name='Ação')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='ID do documento')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoria de resgate (evento)',
                'verbose_name_plural': 'Auditorias de resgate (evento)',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='oficiodocumentovinculo',
            name='eventos_oficiodocumentovinculo_unique',
        ),
        migrations.AddField(
            model_name='eventodocumentosugestao',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_documento_sugestoes', to='contenttypes.contenttype', verbose_name='Tipo do documento'),
        ),
        migrations.AddField(
            model_name='eventoresgateauditoria',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_resgates_documento', to='contenttypes.contenttype', verbose_name='Tipo do documento'),
        ),
        migrations.AddField(
            model_name='eventoresgateauditoria',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resgates_auditoria', to='eventos.evento', verbose_name='Evento'),
        ),
        migrations.RemoveField(
            model_name='oficiodocumentovinculo',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='oficiodocumentovinculo',
            name='oficio',
        ),
        migrations.AddConstraint(
            model_name='eventodocumentosugestao',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='eventos_eventodocumentosugestao_ct_object_unique'),
        ),
        migrations.DeleteModel(
            name='OficioDocumentoVinculo',
        ),
    ]
