# Generated by Django 6.0.1 on 2026-04-22 16:45

import django.db.models.deletion
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_config_pt_sede_chefia_coord'),
        ('eventos', '0056_evento_resgate_remove_oficio_documento_vinculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioAssinaturaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token público')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ASSINADO', 'Assinado'), ('INVALIDADO', 'Invalidado'), ('EXPIRADO', 'Expirado')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status da assinatura')),
                ('nome_assinante_esperado', models.CharField(blank=True, default='', max_length=160, verbose_name='Nome do assinante esperado')),
                ('cpf_esperado', models.CharField(blank=True, default='', max_length=14, verbose_name='CPF esperado')),
                ('telefone_esperado', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone esperado')),
                ('telefone_mascarado_exibido', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefone mascarado exibido')),
                ('cpf_prefixo_confirmado', models.CharField(blank=True, default='', max_length=5, verbose_name='Prefixo de CPF confirmado')),
                ('cpf_confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='CPF confirmado em')),
                ('telefone_confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='Telefone confirmado em')),
                ('fonte_escolhida', models.CharField(blank=True, choices=[('great_vibes', 'Great Vibes'), ('alex_brush', 'Alex Brush'), ('pinyon_script', 'Pinyon Script'), ('allura', 'Allura'), ('arizonia', 'Arizonia'), ('monsieur_la_doulaise', 'Monsieur La Doulaise')], default='', max_length=40, verbose_name='Fonte escolhida')),
                ('pdf_original_congelado', models.FileField(blank=True, null=True, upload_to=eventos.models.oficio_assinatura_upload_to, verbose_name='PDF original congelado')),
                ('hash_pdf_original', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash SHA-256 do PDF original')),
                ('pdf_assinado_final', models.FileField(blank=True, null=True, upload_to=eventos.models.oficio_assinatura_upload_to, verbose_name='PDF assinado final')),
                ('hash_pdf_assinado', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash SHA-256 do PDF assinado')),
                ('assinado_em', models.DateTimeField(blank=True, null=True, verbose_name='Assinado em')),
                ('assinado_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da assinatura')),
                ('assinado_user_agent', models.TextField(blank=True, default='', verbose_name='User agent da assinatura')),
                ('auditoria', models.JSONField(blank=True, default=dict, verbose_name='Auditoria')),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assinante_esperado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_assinatura_oficio', to='cadastros.viajante', verbose_name='Assinante esperado')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_oficio', to='eventos.oficio', verbose_name='Ofício')),
            ],
            options={
                'verbose_name': 'Pedido de assinatura de ofício',
                'verbose_name_plural': 'Pedidos de assinatura de ofício',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
