# Generated by Django 6.0.1 on 2026-04-22 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0057_oficioassinaturapedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oficioassinaturapedido',
            name='criado_por_nome',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Nome do usuário criador'),
        ),
        migrations.AddField(
            model_name='oficioassinaturapedido',
            name='criado_por_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_assinatura_pedidos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
    ]
