services:
  db:
    image: postgres:16
    container_name: central_viagens_3_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: central_viagens_3
      POSTGRES_USER: central_viagens_user
      POSTGRES_PASSWORD: central_viagens_dev
    ports:
      - "5432:5432"
    volumes:
      - central_viagens_3_pgdata:/var/lib/postgresql/data

volumes:
  central_viagens_3_pgdata:
