# Generated by Django 6.0.3 on 2026-03-18 04:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0021_config_pt_sede_chefia_coord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ModeloJustificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('texto', models.TextField(blank=True, default='', verbose_name='Texto da justificativa')),
                ('is_padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de justificativa',
                'verbose_name_plural': 'Modelos de justificativa',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ModeloMotivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('texto', models.TextField(blank=True, default='', verbose_name='Texto do motivo')),
                ('is_padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de motivo',
                'verbose_name_plural': 'Modelos de motivo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, default='', max_length=20, verbose_name='Número')),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('protocolo', models.CharField(blank=True, default='', max_length=30, verbose_name='Protocolo')),
                ('data_criacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('motivo', models.TextField(blank=True, default='', verbose_name='Motivo')),
                ('custeio_tipo', models.CharField(choices=[('PROPRIO', 'Próprio'), ('EXTERNO', 'Externo')], default='PROPRIO', max_length=20, verbose_name='Tipo de custeio')),
                ('nome_instituicao_custeio', models.CharField(blank=True, default='', max_length=200, verbose_name='Instituição custeante')),
                ('tipo_destino', models.CharField(choices=[('NACIONAL', 'Nacional'), ('INTERNACIONAL', 'Internacional')], default='NACIONAL', max_length=20, verbose_name='Tipo de destino')),
                ('placa', models.CharField(blank=True, default='', max_length=10, verbose_name='Placa (snapshot)')),
                ('modelo_veiculo', models.CharField(blank=True, default='', max_length=120, verbose_name='Modelo (snapshot)')),
                ('combustivel_snapshot', models.CharField(blank=True, default='', max_length=60, verbose_name='Combustível (snapshot)')),
                ('tipo_viatura', models.CharField(blank=True, default='', max_length=30, verbose_name='Tipo de viatura')),
                ('porte_transporte_armas', models.BooleanField(default=False, verbose_name='Porte/transporte de armas')),
                ('motorista_carona', models.BooleanField(default=False, verbose_name='Motorista como carona')),
                ('motorista_oficio_numero', models.CharField(blank=True, default='', max_length=20, verbose_name='Número do ofício do motorista')),
                ('motorista_oficio_ano', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano do ofício do motorista')),
                ('motorista_protocolo', models.CharField(blank=True, default='', max_length=30, verbose_name='Protocolo do motorista')),
                ('quantidade_diarias', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Quantidade de diárias')),
                ('valor_diarias', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor das diárias')),
                ('valor_diarias_extenso', models.CharField(blank=True, default='', max_length=300, verbose_name='Valor por extenso')),
                ('justificativa_texto', models.TextField(blank=True, default='', verbose_name='Justificativa')),
                ('gerar_termo_preenchido', models.BooleanField(default=False, verbose_name='Gerar termo preenchido')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='documentos.evento', verbose_name='Evento (opcional)')),
                ('modelo_justificativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='documentos.modelojustificativa', verbose_name='Modelo de justificativa')),
                ('modelo_motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='documentos.modelomotivo', verbose_name='Modelo de motivo')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_como_motorista', to='cadastros.viajante', verbose_name='Motorista')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='cadastros.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ofício',
                'verbose_name_plural': 'Ofícios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=200, verbose_name='Título')),
                ('texto', models.TextField(blank=True, default='', verbose_name='Texto')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas', to='documentos.modelojustificativa', verbose_name='Modelo (opcional)')),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificativas', to='documentos.oficio', verbose_name='Ofício (opcional)')),
            ],
            options={
                'verbose_name': 'Justificativa',
                'verbose_name_plural': 'Justificativas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='OficioTrecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1, verbose_name='Ordem')),
                ('origem_nome', models.CharField(blank=True, default='', max_length=200, verbose_name='Origem (texto)')),
                ('destino_nome', models.CharField(blank=True, default='', max_length=200, verbose_name='Destino (texto)')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de saída')),
                ('hora_saida', models.TimeField(blank=True, null=True, verbose_name='Hora de saída')),
                ('data_chegada', models.DateField(blank=True, null=True, verbose_name='Data de chegada')),
                ('hora_chegada', models.TimeField(blank=True, null=True, verbose_name='Hora de chegada')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Distância (km)')),
                ('duracao_minutos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração estimada (min)')),
                ('tempo_extra_minutos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo extra (min)')),
                ('is_retorno', models.BooleanField(default=False, verbose_name='Trecho de retorno')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.cidade', verbose_name='Destino')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='documentos.oficio', verbose_name='Ofício')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.cidade', verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Trecho do ofício',
                'verbose_name_plural': 'Trechos do ofício',
                'ordering': ['oficio', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='OficioViajante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_snapshot', models.CharField(blank=True, default='', max_length=160, verbose_name='Nome (snapshot)')),
                ('cargo_snapshot', models.CharField(blank=True, default='', max_length=120, verbose_name='Cargo (snapshot)')),
                ('unidade_snapshot', models.CharField(blank=True, default='', max_length=160, verbose_name='Unidade (snapshot)')),
                ('ordem', models.PositiveSmallIntegerField(default=1, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajantes', to='documentos.oficio', verbose_name='Ofício')),
                ('viajante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes', to='cadastros.viajante', verbose_name='Viajante')),
            ],
            options={
                'verbose_name': 'Viajante do ofício',
                'verbose_name_plural': 'Viajantes do ofício',
                'ordering': ['oficio', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(blank=True, default='', verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='documentos.evento', verbose_name='Evento (opcional)')),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='documentos.oficio', verbose_name='Ofício (opcional)')),
            ],
            options={
                'verbose_name': 'Ordem de serviço',
                'verbose_name_plural': 'Ordens de serviço',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PlanoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(blank=True, default='', verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_trabalho', to='documentos.evento', verbose_name='Evento (opcional)')),
            ],
            options={
                'verbose_name': 'Plano de trabalho',
                'verbose_name_plural': 'Planos de trabalho',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome / identificação')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roteiros', to='documentos.evento', verbose_name='Evento (opcional)')),
            ],
            options={
                'verbose_name': 'Roteiro',
                'verbose_name_plural': 'Roteiros',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='oficio',
            name='roteiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios', to='documentos.roteiro', verbose_name='Roteiro (opcional)'),
        ),
        migrations.CreateModel(
            name='RoteiroTrecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1, verbose_name='Ordem')),
                ('data_saida', models.DateField(blank=True, null=True, verbose_name='Data de saída')),
                ('data_chegada', models.DateField(blank=True, null=True, verbose_name='Data de chegada')),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Distância (km)')),
                ('duracao_minutos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração estimada (min)')),
                ('is_retorno', models.BooleanField(default=False, verbose_name='Trecho de retorno')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.cidade', verbose_name='Destino')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastros.cidade', verbose_name='Origem')),
                ('roteiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='documentos.roteiro', verbose_name='Roteiro')),
            ],
            options={
                'verbose_name': 'Trecho do roteiro',
                'verbose_name_plural': 'Trechos do roteiro',
                'ordering': ['roteiro', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='TermoAutorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(blank=True, default='', verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos', to='documentos.evento', verbose_name='Evento (opcional)')),
                ('oficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos', to='documentos.oficio', verbose_name='Ofício (opcional)')),
            ],
            options={
                'verbose_name': 'Termo de autorização',
                'verbose_name_plural': 'Termos de autorização',
                'ordering': ['-criado_em'],
            },
        ),
    ]
