# Generated by Django 6.0.1 on 2026-04-28 19:21

import django.db.models.deletion
import documentos.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('nome_assinante', models.CharField(max_length=160)),
                ('cpf_assinante', models.CharField(blank=True, default='', max_length=14)),
                ('email_assinante', models.EmailField(blank=True, default='', max_length=254)),
                ('metodo_autenticacao', models.CharField(choices=[('usuario_sistema', 'Usuário do sistema'), ('conta_google', 'Conta Google'), ('login_interno', 'Login interno'), ('validacao_cpf', 'Validação por CPF')], default='usuario_sistema', max_length=40)),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('data_hora_assinatura', models.DateTimeField()),
                ('codigo_verificacao', models.CharField(db_index=True, max_length=32, unique=True)),
                ('hash_pdf_original_sha256', models.CharField(max_length=64)),
                ('hash_pdf_assinado_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('arquivo_pdf_assinado', models.FileField(blank=True, null=True, upload_to=documentos.models.assinatura_documento_upload_to)),
                ('pagina_carimbo', models.PositiveIntegerField(default=1)),
                ('posicao_carimbo_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('valida', 'Válida'), ('revogada', 'Revogada'), ('substituida', 'Substituída')], db_index=True, default='valida', max_length=20)),
                ('motivo_revogacao', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_documentos', to='contenttypes.contenttype')),
                ('usuario_assinante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura de documento',
                'verbose_name_plural': 'Assinaturas de documentos',
                'ordering': ['-data_hora_assinatura', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidacaoAssinaturaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('hash_pdf_enviado', models.CharField(blank=True, default='', max_length=64)),
                ('resultado', models.CharField(choices=[('valido', 'Válido'), ('invalido', 'Inválido'), ('codigo_nao_encontrado', 'Código não encontrado'), ('arquivo_sem_codigo', 'Arquivo sem código')], max_length=40)),
                ('observacao', models.TextField(blank=True, default='')),
                ('assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validacoes', to='documentos.assinaturadocumento')),
            ],
            options={
                'verbose_name': 'Validação de assinatura',
                'verbose_name_plural': 'Validações de assinatura',
                'ordering': ['-data_hora', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='assinaturadocumento',
            index=models.Index(fields=['content_type', 'object_id', 'status'], name='documentos__content_ce16b7_idx'),
        ),
    ]
