# Generated by Django 6.0.3 on 2026-03-18 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrar_justificativas_de_oficios(apps, schema_editor):
    """
    Migra Oficio.justificativa_texto → Justificativa vinculada ao Ofício.
    Executa apenas para ofícios que possuam texto de justificativa não vazio
    e que ainda não tenham uma Justificativa associada.
    """
    Oficio = apps.get_model('documentos', 'Oficio')
    Justificativa = apps.get_model('documentos', 'Justificativa')
    for oficio in Oficio.objects.filter(justificativa_texto__gt=''):
        if not Justificativa.objects.filter(oficio=oficio).exists():
            Justificativa.objects.create(
                oficio=oficio,
                titulo='',
                texto=oficio.justificativa_texto,
                modelo_id=oficio.modelo_justificativa_id,
                status='RASCUNHO',
            )


def descartar_justificativas_sem_oficio(apps, schema_editor):
    """
    Remove registros de Justificativa que não possuam ofício vinculado.
    Esses registros não podem satisfazer a nova restrição NOT NULL.
    Eles são descartados pois não há Ofício identificável ao qual associá-los.
    """
    Justificativa = apps.get_model('documentos', 'Justificativa')
    Justificativa.objects.filter(oficio__isnull=True).delete()


def migrar_conteudo_para_texto(apps, schema_editor):
    """Copia o campo 'conteudo' de TermoAutorizacao para o novo campo 'texto'."""
    TermoAutorizacao = apps.get_model('documentos', 'TermoAutorizacao')
    for termo in TermoAutorizacao.objects.exclude(conteudo=''):
        termo.texto = termo.conteudo
        termo.save(update_fields=['texto'])


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_config_pt_sede_chefia_coord'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        # ── TermoAutorizacao: adicionar novos campos ──────────────────────────
        migrations.AddField(
            model_name='termoautorizacao',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='termoautorizacao',
            name='ano',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='termoautorizacao',
            name='data_criacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de criação'),
        ),
        migrations.AddField(
            model_name='termoautorizacao',
            name='texto',
            field=models.TextField(blank=True, default='', verbose_name='Texto do termo'),
        ),
        migrations.AddField(
            model_name='termoautorizacao',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='termoautorizacao',
            name='roteiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos', to='documentos.roteiro', verbose_name='Roteiro (opcional)'),
        ),
        migrations.AddField(
            model_name='termoautorizacao',
            name='viajante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termos', to='cadastros.viajante', verbose_name='Viajante (opcional)'),
        ),
        # ── TermoAutorizacao: migrar conteudo → texto e remover conteudo ─────
        migrations.RunPython(migrar_conteudo_para_texto, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='termoautorizacao',
            name='conteudo',
        ),
        # ── Justificativa: adicionar observacoes ──────────────────────────────
        migrations.AddField(
            model_name='justificativa',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        # ── Justificativa: migrar dados de Oficio.justificativa_texto ─────────
        migrations.RunPython(migrar_justificativas_de_oficios, migrations.RunPython.noop),
        # ── Justificativa: remover registros órfãos (sem ofício) ──────────────
        migrations.RunPython(descartar_justificativas_sem_oficio, migrations.RunPython.noop),
        # ── Justificativa: tornar oficio obrigatório (NOT NULL, CASCADE) ──────
        migrations.AlterField(
            model_name='justificativa',
            name='oficio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativas', to='documentos.oficio', verbose_name='Ofício'),
        ),
        migrations.AlterField(
            model_name='justificativa',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Título / assunto'),
        ),
    ]
