# Generated by Django 5.2.12 on 2026-04-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_rebuild_assinatura_schema_if_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturadocumento',
            name='assinatura_pdf_tecnica_status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='assinaturadocumento',
            name='certificado_issuer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assinaturadocumento',
            name='certificado_serial',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='assinaturadocumento',
            name='certificado_subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='validacaoassinaturadocumento',
            name='status_assinatura_pdf',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
