# Generated by Django 6.0.1 on 2026-04-21 18:43

import assinaturas.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_tipo', models.CharField(help_text='Ex.: eventos.EventoAnexoSolicitante (app_label.ModelName)', max_length=120, verbose_name='Tipo do documento')),
                ('documento_id', models.PositiveIntegerField(verbose_name='ID do registo')),
                ('campo_arquivo', models.CharField(default='arquivo', max_length=80, verbose_name='Campo ficheiro no model')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Token do link')),
                ('arquivo_original', models.FileField(upload_to=assinaturas.models._upload_original, verbose_name='Copia do PDF original (envio)')),
                ('arquivo_assinado', models.FileField(blank=True, null=True, upload_to=assinaturas.models._upload_assinado, verbose_name='PDF assinado')),
                ('arquivo_backup_documento', models.FileField(blank=True, null=True, upload_to=assinaturas.models._upload_backup, verbose_name='Backup do ficheiro no documento antes de substituir')),
                ('nome_assinante', models.CharField(blank=True, default='', max_length=200, verbose_name='Nome do assinante')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('assinado', 'Assinado')], db_index=True, default='pendente', max_length=20, verbose_name='Estado')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('drive_parent_folder_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID pasta pai no Drive')),
                ('drive_target_filename', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do ficheiro no Drive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('usuario_drive', models.ForeignKey(blank=True, help_text='Se preenchido com parent e nome, tenta substituir o PDF no Drive apos assinar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_drive_sync', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador para sincronizar Drive')),
            ],
            options={
                'verbose_name': 'Assinatura de documento',
                'verbose_name_plural': 'Assinaturas de documentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
