# Generated by Django 5.2.12 on 2026-04-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturadocumento',
            name='arquivo_assinado_sha256',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='SHA-256 do PDF assinado'),
        ),
        migrations.AddField(
            model_name='assinaturadocumento',
            name='arquivo_original_sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='SHA-256 do PDF original (envio)'),
        ),
        migrations.AddField(
            model_name='assinaturadocumento',
            name='drive_sync_error',
            field=models.TextField(blank=True, default='', help_text='Preenchido se a assinatura local tiver sucesso mas o Drive falhar.', verbose_name='Ultimo erro de sincronizacao com o Drive'),
        ),
        migrations.AddField(
            model_name='assinaturadocumento',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Apos esta data o link deixa de aceitar assinatura. Null = legado sem expiracao.', null=True, verbose_name='Expira em'),
        ),
        migrations.AddField(
            model_name='assinaturadocumento',
            name='nome_assinante_normalizado',
            field=models.CharField(blank=True, default='', help_text='NFKC, espacos colapsados, casefold — comparacao e registo.', max_length=220, verbose_name='Nome normalizado (auditoria)'),
        ),
    ]
