# Generated by Django 6.0.1 on 2026-04-21 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email Google')),
                ('access_token_encrypted', models.TextField(blank=True, default='', verbose_name='Access token (criptografado)')),
                ('refresh_token_encrypted', models.TextField(blank=True, default='', verbose_name='Refresh token (criptografado)')),
                ('token_uri', models.URLField(blank=True, default='', verbose_name='Token URI')),
                ('client_id', models.CharField(blank=True, default='', max_length=255, verbose_name='OAuth client ID')),
                ('scopes', models.JSONField(blank=True, default=list, verbose_name='Scopes')),
                ('expiry', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('root_folder_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Root folder ID')),
                ('root_folder_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Root folder name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_integration', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Integracao Google Drive',
                'verbose_name_plural': 'Integracoes Google Drive',
            },
        ),
    ]
