# Generated by Django 5.2.12 on 2026-04-29 19:26

import django.db.models.deletion
import prestacao_contas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0021_config_pt_sede_chefia_coord'),
        ('eventos', '0058_oficioassinaturapedido_criado_por_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestacaoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servidor', models.CharField(blank=True, default='', max_length=180, verbose_name='Nome do servidor')),
                ('rg_servidor', models.CharField(blank=True, default='', max_length=30, verbose_name='RG do servidor')),
                ('cpf_servidor', models.CharField(blank=True, default='', max_length=14, verbose_name='CPF do servidor')),
                ('cargo_servidor', models.CharField(blank=True, default='', max_length=120, verbose_name='Cargo do servidor')),
                ('status_rt', models.CharField(choices=[('pendente', 'Pendente'), ('rascunho', 'Rascunho'), ('gerado', 'Gerado')], db_index=True, default='pendente', max_length=20, verbose_name='Status do RT')),
                ('rt_atualizado_em', models.DateTimeField(blank=True, null=True, verbose_name='RT atualizado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes_contas', to='eventos.oficio')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestacoes_contas', to='cadastros.viajante')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioTecnicoPrestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servidor', models.CharField(blank=True, default='', max_length=180)),
                ('rg_servidor', models.CharField(blank=True, default='', max_length=30)),
                ('cpf_servidor', models.CharField(blank=True, default='', max_length=14)),
                ('cargo_servidor', models.CharField(blank=True, default='', max_length=120)),
                ('diaria', models.CharField(blank=True, default='', max_length=80)),
                ('translado', models.CharField(blank=True, default='', max_length=80)),
                ('passagem', models.CharField(blank=True, default='', max_length=80)),
                ('motivo', models.TextField(blank=True, default='')),
                ('atividade', models.TextField(blank=True, default='')),
                ('conclusao', models.TextField(blank=True, default='')),
                ('medidas', models.TextField(blank=True, default='')),
                ('informacoes_complementares', models.TextField(blank=True, default='')),
                ('arquivo_docx', models.FileField(blank=True, null=True, upload_to=prestacao_contas.models._rt_upload_to)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to=prestacao_contas.models._rt_upload_to)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('gerado', 'Gerado')], db_index=True, default='rascunho', max_length=20)),
                ('data_geracao', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_tecnicos_gerados', to=settings.AUTH_USER_MODEL)),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_tecnicos_prestacao', to='eventos.oficio')),
                ('prestacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio_tecnico', to='prestacao_contas.prestacaoconta')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_tecnicos_prestacao', to='cadastros.viajante')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='prestacaoconta',
            constraint=models.UniqueConstraint(condition=models.Q(('servidor__isnull', False)), fields=('oficio', 'servidor'), name='prestacao_conta_oficio_servidor_unique'),
        ),
    ]
