# Generated by Django 5.2.12 on 2026-04-29 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacao_contas', '0004_sync_sqlite_relatorio_campos_restantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriotecnicoprestacao',
            name='atividade_codigos',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='relatoriotecnicoprestacao',
            name='combustivel',
            field=models.CharField(blank=True, default='Cartao Prime', max_length=80),
        ),
        migrations.AddField(
            model_name='relatoriotecnicoprestacao',
            name='teve_passagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relatoriotecnicoprestacao',
            name='teve_translado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relatoriotecnicoprestacao',
            name='unidade_servidor',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='relatoriotecnicoprestacao',
            name='valor_passagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='relatoriotecnicoprestacao',
            name='valor_translado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='TextoPadraoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('oficio_motivo_viagem', 'Oficio - Motivo de viagem'), ('relatorio_tecnico_conclusao', 'RT - Conclusao'), ('relatorio_tecnico_medidas', 'RT - Medidas'), ('relatorio_tecnico_informacoes_complementares', 'RT - Informacoes complementares')], db_index=True, max_length=60)),
                ('titulo', models.CharField(max_length=160)),
                ('texto', models.TextField()),
                ('is_padrao', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textos_padrao_documento_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['categoria', 'ordem', 'titulo'],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'titulo'), name='texto_padrao_documento_categoria_titulo_unique')],
            },
        ),
    ]
