# Generated by Django 5.2.12 on 2026-04-30 13:20

import django.core.validators
import prestacao_contas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestacao_contas', '0006_seed_textos_padrao_rt'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacaoconta',
            name='comprovante_transferencia',
            field=models.FileField(blank=True, null=True, upload_to=prestacao_contas.models._comprovante_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprovante de transferencia'),
        ),
        migrations.AddField(
            model_name='prestacaoconta',
            name='dados_db',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados do DB'),
        ),
        migrations.AddField(
            model_name='prestacaoconta',
            name='db_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='DB atualizado em'),
        ),
        migrations.AddField(
            model_name='prestacaoconta',
            name='descricao_evento',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Descricao do evento'),
        ),
        migrations.AddField(
            model_name='prestacaoconta',
            name='despacho_pdf',
            field=models.FileField(blank=True, null=True, upload_to=prestacao_contas.models._despacho_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Despacho PDF'),
        ),
        migrations.AddField(
            model_name='prestacaoconta',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida')], db_index=True, default='rascunho', max_length=20, verbose_name='Status da prestacao'),
        ),
        migrations.AddField(
            model_name='prestacaoconta',
            name='status_db',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('rascunho', 'Rascunho'), ('gerado', 'Gerado')], db_index=True, default='pendente', max_length=20, verbose_name='Status do DB'),
        ),
    ]
