from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views, views_global

app_name = 'eventos'

urlpatterns = [
    path('', login_required(views_global.documentos_hub), name='lista'),
    path('oficios/', login_required(views_global.oficio_global_lista), name='oficios-global'),
    path('roteiros/', login_required(views_global.roteiro_global_lista), name='roteiros-global'),
    path('documentos/', login_required(views_global.documentos_hub), name='documentos-hub'),
    path('documentos/planos-trabalho/', login_required(views_global.planos_trabalho_global), name='documentos-planos-trabalho'),
    path('documentos/ordens-servico/', login_required(views_global.ordens_servico_global), name='documentos-ordens-servico'),
    path('documentos/justificativas/', login_required(views_global.justificativas_global), name='documentos-justificativas'),
    path('documentos/termos/', login_required(views_global.termos_global), name='documentos-termos'),
    path('documentos/avulsos/novo/', login_required(views_global.documento_avulso_novo), name='documentos-avulsos-novo'),
    path('documentos/avulsos/<int:pk>/editar/', login_required(views_global.documento_avulso_editar), name='documentos-avulsos-editar'),
    path('documentos/avulsos/<int:pk>/download/<str:formato>/', login_required(views_global.documento_avulso_download), name='documentos-avulsos-download'),
    path('simulacao-diarias/', login_required(views_global.simulacao_diarias_global), name='simulacao-diarias'),
    path('modelos-motivo/', login_required(views.modelos_motivo_lista), name='modelos-motivo-lista'),
    path('modelos-motivo/cadastrar/', login_required(views.modelos_motivo_cadastrar), name='modelos-motivo-cadastrar'),
    path('modelos-motivo/<int:pk>/editar/', login_required(views.modelos_motivo_editar), name='modelos-motivo-editar'),
    path('modelos-motivo/<int:pk>/excluir/', login_required(views.modelos_motivo_excluir), name='modelos-motivo-excluir'),
    path('modelos-motivo/<int:pk>/definir-padrao/', login_required(views.modelos_motivo_definir_padrao), name='modelos-motivo-definir-padrao'),
    path('modelos-motivo/<int:pk>/texto/', login_required(views.modelo_motivo_texto_api), name='modelos-motivo-texto-api'),
    path('modelos-justificativa/', login_required(views.modelos_justificativa_lista), name='modelos-justificativa-lista'),
    path('modelos-justificativa/cadastrar/', login_required(views.modelos_justificativa_cadastrar), name='modelos-justificativa-cadastrar'),
    path('modelos-justificativa/<int:pk>/editar/', login_required(views.modelos_justificativa_editar), name='modelos-justificativa-editar'),
    path('modelos-justificativa/<int:pk>/excluir/', login_required(views.modelos_justificativa_excluir), name='modelos-justificativa-excluir'),
    path('modelos-justificativa/<int:pk>/definir-padrao/', login_required(views.modelos_justificativa_definir_padrao), name='modelos-justificativa-definir-padrao'),
    path('modelos-justificativa/<int:pk>/texto/', login_required(views.modelo_justificativa_texto_api), name='modelos-justificativa-texto-api'),
    path('oficio/novo/', login_required(views.oficio_novo), name='oficio-novo'),
    path('oficio/<int:pk>/editar/', login_required(views.oficio_editar), name='oficio-editar'),
    path('oficio/<int:pk>/excluir/', login_required(views.oficio_excluir), name='oficio-excluir'),
    path('oficio/<int:pk>/step1/', login_required(views.oficio_step1), name='oficio-step1'),
    path('oficio/step1/viajantes/', login_required(views.oficio_step1_viajantes_api), name='oficio-step1-viajantes-api'),
    path('oficio/step2/motoristas/', login_required(views.oficio_step2_motoristas_api), name='oficio-step2-motoristas-api'),
    path('oficio/step2/veiculos/', login_required(views.oficio_step2_veiculos_busca_api), name='oficio-step2-veiculos-busca-api'),
    path('oficio/step2/veiculo/', login_required(views.oficio_step2_veiculo_api), name='oficio-step2-veiculo-api'),
    path('oficio/<int:pk>/step2/', login_required(views.oficio_step2), name='oficio-step2'),
    path('oficio/<int:pk>/step3/', login_required(views.oficio_step3), name='oficio-step3'),
    path('oficio/<int:pk>/step3/calcular-diarias/', login_required(views.oficio_step3_calcular_diarias), name='oficio-step3-calcular-diarias'),
    path('oficio/<int:pk>/justificativa/', login_required(views.oficio_justificativa), name='oficio-justificativa'),
    path('oficio/<int:pk>/documentos/', login_required(views.oficio_documentos), name='oficio-documentos'),
    path('oficio/<int:pk>/documentos/<str:tipo_documento>/<str:formato>/', login_required(views.oficio_documento_download), name='oficio-documento-download'),
    path('oficio/<int:pk>/step4/', login_required(views.oficio_step4), name='oficio-step4'),
    path('trechos/<int:pk>/calcular-km/', login_required(views.trecho_calcular_km), name='trecho-calcular-km'),
    path('trechos/estimar/', login_required(views.estimar_km_por_cidades), name='trechos-estimar'),
    path('roteiros/avulso/novo/', login_required(views.roteiro_avulso_cadastrar), name='roteiro-avulso-cadastrar'),
    path('roteiros/avulso/<int:pk>/editar/', login_required(views.roteiro_avulso_editar), name='roteiro-avulso-editar'),
]
